### ISSUE TITLE
digital ocean dns cert problem

### ISSUE THREAD

**Issue by mike-gracia** [linuxserver/docker-letsencrypt#109]
not sure what is wrong with the digitalocean dns script, going to switch to another but i thought i would put this here for you.

```
2018-02-05T16:54:14.217662999Z Generating new certificate
2018-02-05T16:54:15.751941268Z Saving debug log to /var/log/letsencrypt/letsencrypt.log
2018-02-05T16:54:15.760014451Z Plugins selected: Authenticator dns-digitalocean, Installer None
2018-02-05T16:54:16.087488366Z Obtaining a new certificate
2018-02-05T16:54:18.027681186Z Performing the following challenges:
2018-02-05T16:54:18.027880537Z dns-01 challenge for mydom.stream
2018-02-05T16:54:18.028257255Z dns-01 challenge for www.mydom.stream
2018-02-05T16:54:18.028421826Z dns-01 challenge for ftp.mydom.stream
2018-02-05T16:54:18.028642982Z dns-01 challenge for cloud.mydom.stream
2018-02-05T16:54:18.028938013Z Unsafe permissions on credentials configuration file: /config/dns-conf/digitalocean.ini
2018-02-05T16:54:18.463314298Z Cleaning up challenges
2018-02-05T16:54:18.715121116Z Encountered exception during recovery
2018-02-05T16:54:18.715370816Z Unable to determine base domain for mydom.stream using names: [u'mydom.stream', u'stream'].
2018-02-05T16:54:18.715379875Z Traceback (most recent call last):
2018-02-05T16:54:18.715383334Z   File "/usr/lib/python2.7/site-packages/certbot/error_handler.py", line 100, in _call_registered
2018-02-05T16:54:18.715386699Z     self.funcs[-1]()
2018-02-05T16:54:18.715389586Z   File "/usr/lib/python2.7/site-packages/certbot/auth_handler.py", line 284, in _cleanup_challenges
2018-02-05T16:54:18.715392759Z     self.auth.cleanup(achalls)
2018-02-05T16:54:18.715395531Z   File "/usr/lib/python2.7/site-packages/certbot/plugins/dns_common.py", line 76, in cleanup
2018-02-05T16:54:18.715398893Z     self._cleanup(domain, validation_domain_name, validation)
2018-02-05T16:54:18.715401855Z   File "/usr/lib/python2.7/site-packages/certbot_dns_digitalocean/dns_digitalocean.py", line 50, in _cleanup
2018-02-05T16:54:18.715405130Z     self._get_digitalocean_client().del_txt_record(domain, validation_name, validation)
2018-02-05T16:54:18.715408256Z   File "/usr/lib/python2.7/site-packages/certbot_dns_digitalocean/dns_digitalocean.py", line 116, in del_txt_record
2018-02-05T16:54:18.715415656Z     domain = self._find_domain(domain_name)
2018-02-05T16:54:18.715418615Z   File "/usr/lib/python2.7/site-packages/certbot_dns_digitalocean/dns_digitalocean.py", line 163, in _find_domain
2018-02-05T16:54:18.715421717Z     .format(domain_name, domain_name_guesses))
2018-02-05T16:54:18.715424497Z PluginError: Unable to determine base domain for mydom.stream using names: [u'mydom.stream', u'stream'].
2018-02-05T16:54:18.716174821Z Unable to determine base domain for mydom.stream using names: [u'mydom.stream', u'stream'].
2018-02-05T16:54:18.761892428Z ERROR: Cert does not exist! Please see the validation error above. Make sure you entered correct credentials into the /config/dns 
```

**Comment by aptalca** [comment]
ahh it seems the plugin doesn't recognize .stream as a valid extension and expects the domain to be one of the traditional ones like .com .net etc.

The plugin is maintained by certbot (official letsencrypt client) and here's the line causing the error: https://github.com/certbot/certbot/blob/master/certbot-dns-digitalocean/certbot_dns_digitalocean/dns_digitalocean.py#L162

Do you mind opening an issue over there?

Thanks

**Comment by mike-gracia** [comment]
Yeah I will before the end of the end of the day. Switched to cloudflare and still having some trouble. Is there something I need to setup in .conf file to get this working? I have an old default file but maybe you have updated it. I have ports 443 and 80 forwarded to this container if that matters.

```
IMPORTANT NOTES:
2018-02-05T17:35:56.331008244Z  - The following errors were reported by the server:
2018-02-05T17:35:56.331049762Z
2018-02-05T17:35:56.331065858Z    Domain: cloud.mydom.stream
2018-02-05T17:35:56.331081269Z    Type:   connection
2018-02-05T17:35:56.331095668Z    Detail: DNS problem: NXDOMAIN looking up TXT for
2018-02-05T17:35:56.331110942Z    _acme-challenge.cloud.mydom.stream
2018-02-05T17:35:56.331125192Z
2018-02-05T17:35:56.331138519Z    Domain: ftp.mydom.stream
2018-02-05T17:35:56.331152118Z    Type:   connection
2018-02-05T17:35:56.331166659Z    Detail: DNS problem: NXDOMAIN looking up TXT for
2018-02-05T17:35:56.331180885Z    _acme-challenge.ftp.mydom.stream
2018-02-05T17:35:56.331196162Z
2018-02-05T17:35:56.331210091Z    Domain: www.mydom.stream
2018-02-05T17:35:56.331224511Z    Type:   connection
2018-02-05T17:35:56.331239192Z    Detail: DNS problem: NXDOMAIN looking up TXT for
2018-02-05T17:35:56.331254385Z    _acme-challenge.www.mydom.stream
2018-02-05T17:35:56.331269662Z
2018-02-05T17:35:56.331313579Z    To fix these errors, please make sure that your domain name was
2018-02-05T17:35:56.331330478Z    entered correctly and the DNS A/AAAA record(s) for that domain
2018-02-05T17:35:56.331339566Z    contain(s) the right IP address. Additionally, please check that
2018-02-05T17:35:56.331347792Z    your computer has a publicly routable IP address and that no
2018-02-05T17:35:56.331356576Z    firewalls are preventing the server from communicating with the
2018-02-05T17:35:56.331364733Z    client. If you're using the webroot plugin, you should also verify
2018-02-05T17:35:56.331373034Z    that you are serving files from the webroot path you provided.
2018-02-05T17:35:56.331383721Z  - The following errors were reported by the server:
2018-02-05T17:35:56.331396220Z
2018-02-05T17:35:56.331408934Z    Domain: mydom.stream
2018-02-05T17:35:56.331419291Z    Type:   unauthorized
2018-02-05T17:35:56.331427103Z    Detail: No TXT record found at _acme-challenge.mydom.stream
2018-02-05T17:35:56.331435049Z
2018-02-05T17:35:56.331442471Z    To fix these errors, please make sure that your domain name was
2018-02-05T17:35:56.331450464Z    entered correctly and the DNS A/AAAA record(s) for that domain
2018-02-05T17:35:56.381561575Z    contain(s) the right IP address.
2018-02-05T17:35:56.381590210Z  - Your account credentials have been saved in your Certbot
2018-02-05T17:35:56.381594745Z    configuration directory at /etc/letsencrypt. You should make a
2018-02-05T17:35:56.381597883Z    secure backup of this folder now. This configuration directory will
2018-02-05T17:35:56.381601001Z    also contain certificates and private keys obtained by Certbot so
2018-02-05T17:35:56.381603667Z    making regular backups of this folder is ideal.
2018-02-05T17:35:56.383804594Z ERROR: Cert does not exist! Please see the validation error above. Make sure you entered correct credentials into the /config/dns-conf/cloudflare.ini file.
```

**Comment by mike-gracia** [comment]
Hey thanks for the help, I think I figured it out, needed to change my domain's nameservers. Now im in 'Website not active (DNS modification pending)' with cloudflare, i asume once the change is processed this, plugin is going to work.
