### ISSUE TITLE
Certbot gives a version conflict error

### ISSUE THREAD

**Issue by Nreall** [linuxserver/docker-letsencrypt#379]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
Normal certificate request procedure to Lets Encrypt

## Current Behavior
The Lets Encrypt Certbot gives a Version conflict error.

using http or duckdns (only tested these 2 options) the error occurs with the "latest" build (0.40.1-ls76)

## Steps to Reproduce
1. Using the Duckdns or HTTP option

## Environment
**OS: OpenMediaVault 4.1.22-1**     
**CPU architecture:** x86_64
**How docker service was installed:**      
Using portainer

## Docker logs
`Traceback (most recent call last):
  File "/usr/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.7/site-packages/certbot/main.py", line 1348, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/usr/lib/python3.7/site-packages/certbot/plugins/disco.py", line 208, in find_all
    plugin_ep = PluginEntryPoint(entry_point)
  File "/usr/lib/python3.7/site-packages/certbot/plugins/disco.py", line 50, in __init__
    self.plugin_cls = entry_point.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2442, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2465, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (cryptography 2.6.1 (/usr/lib/python3.7/site-packages), Requirement.parse('cryptography>=2.8'), {'PyOpenSSL'})`

**Already found a workaround, build 0.40.1-ls75 seems to not have this issue.**

**Comment by ernie58** [comment]
Got this error as well, using previous versions helped for me as well

these are my logs:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    501
User gid:    501
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 
generating self-signed keys in /config/keys, you can replace these with your own keys if required
Generating a RSA private key
.........................................+++++
.........................................+++++
writing new private key to '/config/keys/cert.key'
-----
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing... 
Variables set:
PUID=501
PGID=501
TZ=Europe/Brussels
URL=******
SUBDOMAINS=******
EXTRA_DOMAINS=********
ONLY_SUBDOMAINS=true
DHLEVEL=2048
VALIDATION=http
DNSPLUGIN=
EMAIL=*************
STAGING=false
Created donoteditthisfile.conf
Creating DH parameters for additional security. This may take a very long time. There will be another message once this process is completed
Generating DH parameters, 2048 bit long safe prime, generator 2
This is going to take a long time
.............+.............................+........................................+.........................................................................................................................+...............................................................................................+...............+..............................................................................................................................................+....................+.+....................................+...............+....................................................................................................+.+....+.........................................................................................................................+.............................................................................................................+..............++*++*++*++*
DH parameters successfully created - 2048 bits
SUBDOMAINS entered, processing
SUBDOMAINS entered, processing
Only subdomains, no URL in cert
Sub-domains processed are:  ******
EXTRA_DOMAINS entered, processing
Extra domains processed are:  -d ***** -d *******
E-mail address entered: **************
http validation is selected
Generating new certificate
An unexpected error occurred:
pkg_resources.ContextualVersionConflict: (cryptography 2.6.1 (/usr/lib/python3.7/site-packages), Requirement.parse('cryptography>=2.8'), {'PyOpenSSL'})
Please see the logfile '/tmp/tmpt5f6jg9_/log' for more details.
ERROR: Cert does not exist! Please see the validation error above. The issue may be due to incorrect dns or port forwarding settings. Please fix your settings and recreate the container
```
The log inside the container is:
```
root@7a6944f7c023:/# cat /tmp/tmpt5f6jg9_/log
2019-11-20 12:15:44,082:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.7/site-packages/certbot/main.py", line 1348, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/usr/lib/python3.7/site-packages/certbot/plugins/disco.py", line 208, in find_all
    plugin_ep = PluginEntryPoint(entry_point)
  File "/usr/lib/python3.7/site-packages/certbot/plugins/disco.py", line 50, in __init__
    self.plugin_cls = entry_point.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2442, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2465, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (cryptography 2.6.1 (/usr/lib/python3.7/site-packages), Requirement.parse('cryptography>=2.8'), {'PyOpenSSL'})
2019-11-20 12:15:44,082:ERROR:certbot.log:An unexpected error occurred:
```

**Comment by Tuumke** [comment]
+1
Reported it in Discord first. Is being looked into (as in, new build to check if there are any updated features).

**Comment by aptalca** [comment]
Thanks for the heads up. The system installed cryptography did not get updated due to pip issue https://github.com/pypa/pip/issues/988
We'll fix this shortly.

**Comment by JOduMonT** [comment]
docker exec letsencrypt cat /tmp/tmpb35q6n6a/log
```
2019-11-20 21:03:22,375:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.7/site-packages/certbot/main.py", line 1348, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/usr/lib/python3.7/site-packages/certbot/plugins/disco.py", line 208, in find_all
    plugin_ep = PluginEntryPoint(entry_point)
  File "/usr/lib/python3.7/site-packages/certbot/plugins/disco.py", line 50, in __init__
    self.plugin_cls = entry_point.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2442, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2465, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (cryptography 2.6.1 (/usr/lib/python3.7/site-packages), Requirement.parse('cryptography>=2.8'), {'PyOpenSSL'})
2019-11-20 21:03:22,375:ERROR:certbot.log:An unexpected error occurred:
```

**Comment by ximon18** [comment]
I'm also seeing the same issue with `linuxserver/letsencrypt` and can also resolve it by reverting to `linuxserver/letsencrypt:0.40.1-ls75`.
